using 'main.bicep'

param containerEnvironmentName = 'auction-env'
param containerRegistryName = 'auctioncr'
param containerAppName = 'auction-api'
param repositoryUrl = 'https://github.com/vpriadilia/auction'
param branch = 'main'
param repositoryToken = '<REDACTED>'
param functionAppName = 'auction-function'
param functionStorageAccountName = 'auctionfuncsa'
