using 'main.bicep'

param containerEnvironmentName = 'auction-env'
param containerRegistryName = 'auctioncr'
param containerAppName = 'auction-api'
param staticWebAppName = 'auction-swa'
param repositoryUrl = 'https://github.com/vpriadilia/auction'
param branch = 'main'
param repositoryToken = '<REDACTED>'
param functionAppName = 'auction-function'
param functionStorageAccountName = 'auctionfuncsa'
param logAnalyticsWorkspaceName = 'auction-logs'
param appInsightsName = 'auction-insights'
param serviceBusNamespaceName = 'auction-bus'
param sqlServerName = 'auction-sql'
param sqlDatabaseName = 'auction-db'
param sqlAadAdminObjectId = 'ebcffb49-deda-4c7f-b648-4ceebdcc8923'
param sqlAadAdminLogin = 'Vitalii Priadilia'
param blobsExtensionSystemKey = '<REDACTED>'
