using 'main.bicep'

param containerEnvironmentName = 'auction-env'
param containerRegistryName = 'auctioncr'
param containerAppName = 'auction-api'
param staticWebAppName = 'auction-swa'
param repositoryUrl = 'https://github.com/vpriadilia/auction'
param branch = 'main'
param repositoryToken = '<REDACTED>'
param functionAppName = 'auction-function'
param functionStorageAccountName = 'auctionfuncsa'
param logAnalyticsWorkspaceName = 'auction-logs'
param appInsightsName = 'auction-insights'
